apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: binaryscanner
  name: {{ .Release.Name }}-blackduck-binaryscanner
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    {{- include "bd.selectorLabels" . | nindent 4 }}
    component: binaryscanner
  template:
    metadata:
      labels:
        {{- include "bd.selectorLabels" . | nindent 8 }}
        component: binaryscanner
      name: {{ .Release.Name }}-blackduck-binaryscanner
    spec:
      containers:
      - command:
        - /docker-entrypoint.sh
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-config
        image: {{ .Values.appCheckRegistry }}/appcheck-worker:{{ .Values.binaryscanner.imageTag }}
        imagePullPolicy: Always
        name: binaryscanner
        ports:
        - containerPort: 3001
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.binaryscanner.limitCpu }}
            memory: {{ .Values.binaryscanner.limitMemory }}
          requests:
            cpu: {{ .Values.binaryscanner.requestCpu }}
            memory: {{ .Values.binaryscanner.requestMemory }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      {{- with .Values.binaryscanner.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.binaryscanner.affinity }}
      affinity:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.binaryscanner.tolerations }}
      tolerations:
      {{ toYaml . | indent 2 }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30