apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "bd.labelsWihtoutVersion" . | nindent 4 }}
    component: cfssl
  name: {{ .Release.Name }}-blackduck-cfssl
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-8888
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    {{- include "bd.selectorLabelsWihtoutVersion" . | nindent 4 }}
    component: cfssl
  type: ClusterIP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: cfssl
  name: {{ .Release.Name }}-blackduck-cfssl
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    {{- include "bd.selectorLabels" . | nindent 4 }}
    component: cfssl
  template:
    metadata:
      labels:
        {{- include "bd.selectorLabels" . | nindent 8 }}
        component: cfssl
      name: {{ .Release.Name }}-blackduck-cfssl
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-config
        image: {{ .Values.registry }}/blackduck-cfssl:{{ .Values.cfssl.imageTag }}
        imagePullPolicy: Always
        {{- include "cfsslLivenessProbe" . | nindent 8 }}
        name: cfssl
        ports:
        - containerPort: 8888
          protocol: TCP
        resources:
          limits:
            memory: {{ .Values.cfssl.limitMemory }}
          requests:
            memory: {{ .Values.cfssl.requestMemory }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/cfssl
          name: dir-cfssl
      dnsPolicy: ClusterFirst
      {{- with .Values.cfssl.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.cfssl.affinity }}
      affinity:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.cfssl.tolerations }}
      tolerations:
      {{ toYaml . | indent 2 }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      {{- include "bd.securityContext" . | nindent 6 }}
      terminationGracePeriodSeconds: 30
      volumes:
      {{- include "cfsslPersistentStorage" . | nindent 6 }}

{{- define "cfsslLivenessProbe" -}}
{{- if .Values.enableLivenessProbe -}}
livenessProbe:
  exec:
    command:
    - /usr/local/bin/docker-healthcheck.sh
    - http://localhost:8888/api/v1/cfssl/scaninfo
  failureThreshold: 10
  initialDelaySeconds: 240
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
{{- end -}}
{{- end -}}

{{- define "cfsslPersistentStorage" -}}
{{- if .Values.enablePersistentStorage -}}
- name: dir-cfssl
  persistentVolumeClaim:
    claimName: {{ .Release.Name }}-blackduck-cfssl
{{- else -}}
- emptyDir: {}
  name: dir-cfssl
{{- end -}}
{{- end -}}