apiVersion: v1
data:
  HUB_POSTGRES_ADMIN: blackduck
  HUB_POSTGRES_ENABLE_SSL: "false"
  HUB_POSTGRES_HOST: {{ .Release.Name }}-blackduck-postgres
  HUB_POSTGRES_PORT: "5432"
  HUB_POSTGRES_USER: blackduck_user
kind: ConfigMap
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: postgres
  name: {{ .Release.Name }}-blackduck-db-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  HUB_POSTGRES_ADMIN_PASSWORD_FILE: YmxhY2tkdWNr
  HUB_POSTGRES_POSTGRES_PASSWORD_FILE: YmxhY2tkdWNr
  HUB_POSTGRES_USER_PASSWORD_FILE: YmxhY2tkdWNr
kind: Secret
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: postgres
  name: {{ .Release.Name }}-blackduck-db-creds
  namespace: {{ .Release.Namespace }}
type: Opaque