apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "bd.labelsWihtoutVersion" . | nindent 4 }}
    component: scan
  name: {{ .Release.Name }}-blackduck-scan
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-8443
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "bd.selectorLabelsWihtoutVersion" . | nindent 4 }}
    component: scan
  type: ClusterIP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: scan
  name: {{ .Release.Name }}-blackduck-scan
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    {{- include "bd.selectorLabels" . | nindent 4 }}
    component: scan
  template:
    metadata:
      labels:
        {{- include "bd.selectorLabels" . | nindent 8 }}
        component: scan
      name: {{ .Release.Name }}-blackduck-scan
    spec:
      containers:
      - env:
        - name: HUB_MAX_MEMORY
          value: 2048m
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-config
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-db-config
        image: {{ .Values.registry }}/blackduck-scan:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        {{- include "scanLivenessProbe" . | nindent 8 }}
        name: scan
        ports:
        - containerPort: 8443
          protocol: TCP
        resources:
          limits:
            memory: {{ .Values.scan.limitMemory }}
          requests:
            memory: {{ .Values.scan.requestMemory }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/secrets/HUB_POSTGRES_ADMIN_PASSWORD_FILE
          name: db-passwords
          subPath: HUB_POSTGRES_ADMIN_PASSWORD_FILE
        - mountPath: /tmp/secrets/HUB_POSTGRES_USER_PASSWORD_FILE
          name: db-passwords
          subPath: HUB_POSTGRES_USER_PASSWORD_FILE
        - mountPath: /opt/blackduck/hub/hub-scan/security
          name: dir-scan
      dnsPolicy: ClusterFirst
      {{- with .Values.scan.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.scan.affinity }}
      affinity:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.scan.tolerations }}
      tolerations:
      {{ toYaml . | indent 2 }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      {{- include "bd.securityContext" . | nindent 6 }}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: dir-scan
      - name: db-passwords
        secret:
          defaultMode: 420
          items:
          - key: HUB_POSTGRES_ADMIN_PASSWORD_FILE
            mode: 420
            path: HUB_POSTGRES_ADMIN_PASSWORD_FILE
          - key: HUB_POSTGRES_USER_PASSWORD_FILE
            mode: 420
            path: HUB_POSTGRES_USER_PASSWORD_FILE
          secretName: {{ .Release.Name }}-blackduck-db-creds

{{- define "scanLivenessProbe" -}}
{{- if .Values.enableLivenessProbe -}}
livenessProbe:
  exec:
    command:
    - /usr/local/bin/docker-healthcheck.sh
    - https://127.0.0.1:8443/api/health-checks/liveness
    - /opt/blackduck/hub/hub-scan/security/root.crt
    - /opt/blackduck/hub/hub-scan/security/blackduck_system.crt
    - /opt/blackduck/hub/hub-scan/security/blackduck_system.key
  failureThreshold: 10
  initialDelaySeconds: 240
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
{{- end -}}
{{- end -}}