apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "bd.labelsWihtoutVersion" . | nindent 4 }}
    component: webserver
  name: {{ .Release.Name }}-blackduck-webserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-443
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "bd.selectorLabelsWihtoutVersion" . | nindent 4 }}
    component: webserver
  type: ClusterIP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: webserver
  name: {{ .Release.Name }}-blackduck-webserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    {{- include "bd.selectorLabels" . | nindent 4 }}
    component: webserver
  template:
    metadata:
      labels:
        {{- include "bd.selectorLabels" . | nindent 8 }}
        component: webserver
      name: {{ .Release.Name }}-blackduck-webserver
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-config
        image: {{ .Values.registry }}/blackduck-nginx:{{ .Values.webserver.imageTag }}
        imagePullPolicy: Always
        {{- include "webserverLivenessProbe" . | nindent 8 }}
        name: webserver
        ports:
        - containerPort: 8443
          protocol: TCP
        resources:
          limits:
            memory: {{ .Values.webserver.limitMemory }}
          requests:
            memory: {{ .Values.webserver.requestMemory }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/blackduck/hub/webserver/security
          name: dir-webserver
        - mountPath: /tmp/secrets/WEBSERVER_CUSTOM_CERT_FILE
          name: certificate
          subPath: WEBSERVER_CUSTOM_CERT_FILE
        - mountPath: /tmp/secrets/WEBSERVER_CUSTOM_KEY_FILE
          name: certificate
          subPath: WEBSERVER_CUSTOM_KEY_FILE
      dnsPolicy: ClusterFirst
      {{- with .Values.webserver.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.webserver.affinity }}
      affinity:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.webserver.tolerations }}
      tolerations:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.webserver.securityContext }}
      securityContext:
      {{ toYaml . | indent 2 }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: dir-webserver
      - name: certificate
        secret:
          defaultMode: 292
          secretName: {{ .Release.Name }}-blackduck-webserver-certificate

{{- define "webserverLivenessProbe" -}}
{{- if .Values.enableLivenessProbe -}}
livenessProbe:
  exec:
    command:
    - /usr/local/bin/docker-healthcheck.sh
    - https://localhost:8443/health-checks/liveness
    - /tmp/secrets/WEBSERVER_CUSTOM_CERT_FILE
  failureThreshold: 10
  initialDelaySeconds: 180
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
{{- end -}}
{{- end -}}