apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "bd.labelsWihtoutVersion" . | nindent 4 }}
    component: zookeeper
  name: {{ .Release.Name }}-blackduck-zookeeper
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-2181
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    {{- include "bd.selectorLabelsWihtoutVersion" . | nindent 4 }}
    component: zookeeper
  type: ClusterIP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: zookeeper
  name: {{ .Release.Name }}-blackduck-zookeeper
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    {{- include "bd.selectorLabels" . | nindent 4 }}
    component: zookeeper
  template:
    metadata:
      labels:
        {{- include "bd.selectorLabels" . | nindent 8 }}
        component: zookeeper
      name: {{ .Release.Name }}-blackduck-zookeeper
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-config
        image: {{ .Values.registry }}/blackduck-zookeeper:{{ .Values.zookeeper.imageTag }}
        imagePullPolicy: Always
        {{- include "zookeeperLivenessProbe" . | nindent 8 }}
        name: zookeeper
        ports:
        - containerPort: 2181
          protocol: TCP
        resources:
          limits:
            memory: {{ .Values.zookeeper.limitMemory }}
          requests:
            cpu: {{ .Values.zookeeper.requestCpu }}
            memory: {{ .Values.zookeeper.requestMemory }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/blackduck/zookeeper/data
          name: dir-zookeeper
          subPath: data
        - mountPath: /opt/blackduck/zookeeper/datalog
          name: dir-zookeeper
          subPath: datalog
      dnsPolicy: ClusterFirst
      {{- with .Values.zookeeper.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.zookeeper.affinity }}
      affinity:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.zookeeper.tolerations }}
      tolerations:
      {{ toYaml . | indent 2 }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      {{- include "bd.securityContext" . | nindent 6 }}
      terminationGracePeriodSeconds: 30
      volumes:
      {{- include "zookeeperPersistentStorage" . | nindent 6 }}

{{- define "zookeeperLivenessProbe" -}}
{{- if .Values.enableLivenessProbe -}}
livenessProbe:
  exec:
    command:
    - zkServer.sh
    - status
    - /opt/blackduck/zookeeper/conf/zoo.cfg
  failureThreshold: 10
  initialDelaySeconds: 240
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
{{- end -}}
{{- end -}}

{{- define "zookeeperPersistentStorage" -}}
{{- if .Values.enablePersistentStorage -}}
- name: dir-zookeeper
  persistentVolumeClaim:
    claimName: {{ .Release.Name }}-blackduck-zookeeper
{{- else -}}
- emptyDir: {}
  name: dir-zookeeper
{{- end -}}
{{- end -}}