apiVersion: batch/v1
kind: Job
metadata:
  chart: polaris-jobs
  chartVersion: 0.0.50
  component: polaris-jobs
  componentVersion: 0.0.50
  environment: ${ENVIRONMENT_NAME}
  labels: null
  name: organization-provision-job
  service: organization-provision-job
spec:
  template:
    metadata:
      annotations:
        helm.sh/hook: post-install, post-upgrade
        helm.sh/hook-delete-policy: hook-succeeded
        helm.sh/hook-weight: "100"
      labels:
        chart: polaris-jobs
        chartVersion: 0.0.50
        component: polaris-jobs
        componentVersion: 0.0.50
        environment: ${ENVIRONMENT_NAME}
        service: organization-provision-job
      name: organization-provision-job
    spec:
      containers:
      - env:
        - name: LOGGING_LEVEL
          value: INFO
        - name: ESJC_LOGGING_LEVEL
          value: INFO
        - name: SWIP_ENVIRONMENT_NAME
          value: ${ENVIRONMENT_NAME}
        - name: SWIP_ROOT_DOMAIN
          value: ${POLARIS_ROOT_DOMAIN}
        - name: SWIP_SERVICE_NAME
          value: organization-provision-job
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POLARIS_ENVIRONMENT_NAME
          value: ${ENVIRONMENT_NAME}
        - name: POLARIS_ROOT_DOMAIN
          value: ${POLARIS_ROOT_DOMAIN}
        - name: POLARIS_SERVICE_NAME
          value: organization-provision-job
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SWIP_VAULT_ADDRESS
          value: https://vault:8200
        - name: VAULT_CACERT
          value: /var/run/secrets/vault/ca/ca.crt
        - name: VAULT_CLIENT_KEY
          value: /var/run/secrets/vault/client/tls.key
        - name: VAULT_CLIENT_CERT
          value: /var/run/secrets/vault/client/tls.crt
        - name: ORGANIZATION_PROVISION_AUTH_SERVICE_URL
          value: http://auth-server
        - name: ORGANIZATION_PROVISION_TOOLS_SERVICE_URL
          value: http://tools-service
        - name: REQUIRED_SERVICE_RETRY_SECONDS
          value: "5"
        - name: REQUIRED_SERVICE_RETRY_STOP_MINUTES
          value: "20"
        - name: ORGANIZATION_PROVISION_API_TOKEN_VAULT_PATH
          value: secret/data/auth/public/daemon@api_token
        - name: ORGANIZATION_PROVISION_ORGANIZATION_DESCRIPTION
          valueFrom:
            secretKeyRef:
              key: organization_name
              name: polaris-environment-config
        - name: ORGANIZATION_PROVISION_ORGANIZATION_NAME
          valueFrom:
            configMapKeyRef:
              key: name
              name: polaris-environment-config
        - name: ORGANIZATION_PROVISION_ADMIN_NAME
          valueFrom:
            secretKeyRef:
              key: admin_name
              name: polaris-environment-config
        - name: ORGANIZATION_PROVISION_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              key: admin_username
              name: polaris-environment-config
        - name: ORGANIZATION_PROVISION_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              key: admin_email
              name: polaris-environment-config
        - name: ORGANIZATION_PROVISION_COVERITY_LICENSE
          valueFrom:
            secretKeyRef:
              key: license
              name: coverity-license
        - name: ORGANIZATION_PROVISION_SIGNED_LICENSE
          valueFrom:
            secretKeyRef:
              key: polaris
              name: organization-license
        image: gcr.io/snps-swip-staging/polaris-organization-provision-job:1.0.23653
        imagePullPolicy: IfNotPresent
        name: organization-provision-job
        resources: {}
        volumeMounts:
        - mountPath: /var/run/secrets/vault/client
          name: vault-client
          readOnly: true
        - mountPath: /var/run/secrets/vault/ca
          name: vault-server-ca
          readOnly: true
      imagePullSecrets:
      - name: ${IMAGE_PULL_SECRETS}
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 5000
      volumes:
      - name: vault-client
        secret:
          secretName: vault-read-only
      - name: vault-server-ca
        secret:
          defaultMode: 420
          secretName: vault-tls-certificate-new
